### ISSUE TITLE
Feature Request: Filter by ArtifactType after calling oci Store.Predecessors()

### ISSUE THREAD

**Issue by patrickzheng200** [oras-project/oras-go#453] opened 2023-03-02 07:02 UTC
I'd like to filter manifests by ArtifactType after calling oci Store.Predecessors(), for example, only keeping notary signatures ("application/vnd.cncf.notary.signature"). 
Currently, the ArtifactType field is cut after calling Predecessors(), which is blocking my filtering.

Is it feasible to keep the ArtifactType information for Predecessors()?

**Comment by shizhMSFT** [comment] 2023-03-02 07:05
Extracting `ArtifactType` is not the purpose of the `Predecessors()` and it requires additional I/Os.

@patrickzheng200 If you are interested, you can take a look at the [related `oras` implementation](https://github.com/oras-project/oras/blob/12097db4963d22f934c21b0a6d72543677da2ef5/internal/graph/graph.go#L64-L122).

**Comment by patrickzheng200** [comment] 2023-03-02 07:45
> Extracting `ArtifactType` is not the purpose of the `Predecessors()` and it requires additional I/Os.
> 
> @patrickzheng200 If you are interested, you can take a look at the [related `oras` implementation](https://github.com/oras-project/oras/blob/12097db4963d22f934c21b0a6d72543677da2ef5/internal/graph/graph.go#L64-L122).

@shizhMSFT hmm, to my understanding, Predecessors() serves as the OCI layout substitution of the OCI v1.1 Referrers API in oras-go. Please correct me if I'm wrong. Since Referrers API has the ability to filter by ArtifactType, should we also support this feature in Predecessors()?

**Comment by shizhMSFT** [comment] 2023-03-02 08:50
[Predecessors()](https://pkg.go.dev/oras.land/oras-go/v2/content#PredecessorFinder) is a method to find all predecessors of the current node in terms of the graph. It cares about the nodes themself (i.e. media type, digest, size) but not their metadata (e.g. artifact type). `Predecessors()` applies to all [GraphStorage](https://pkg.go.dev/oras.land/oras-go/v2/content#GraphStorage) where registries are instances of `GraphStorage`.

On the other hand, `Referrers` API works similar to `Predecessors()` but only finds certain types of predecessors (i.e. manifest types.) [iff](https://en.wikipedia.org/wiki/If_and_only_if) the current node is of manifest types. Besides, `Referrers` API also returns `ArtifactType` and `Annotations` of the found predecessors per spec.

![image](https://user-images.githubusercontent.com/32161882/222378297-d689c4a1-3330-40ac-8b58-f4ee22e9c7e6.png)

**Comment by shizhMSFT** [comment] 2023-03-02 08:56
Therefore, `Predecessors()` and `Referrers()` are not interchangeable.

Nonetheless, `Referrers()` can be used as a degraded `Predecessors`. For example, remote repositories:
https://github.com/oras-project/oras-go/blob/96a37c2b359ac1305f70dc31b28c789688d77d0f/registry/remote/repository.go#L365-L378

Meanwhile, `Referrers()` can be implemented using `Predecessors()` with degraded performance.

**Comment by patrickzheng200** [comment] 2023-03-02 08:57
@shizhMSFT thanks for the detailed explanation! So by design, we are not simply substituting Referrers API with Predecessors() in OCI layout. I get the differences now.

**Comment by shizhMSFT** [comment] 2023-03-22 09:13
Closing as a duplicate of #392

**Closed by shizhMSFT** 2023-03-22 09:13 UTC
